version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=26*06*1997!
      - ORACLE_SID=tickets_db
    networks:
      - backend-network

  backend:
    build:
      context: ./ticket-manage-service
      dockerfile: ./ticket-manage-service/Dockerfile
    container_name: ticket-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/tickets_db
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=26*06*1997!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.Oracle12cDialect
      - DB_HOST=oracle-db
    depends_on:
      - oracle-db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
